project_id = "qyritntnyigmustviepw"

[functions.analyze-lyrics]
verify_jwt = false

[functions.analyze-image-style]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-batch-images]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-scene-prompt]
verify_jwt = false

[functions.generate-video-prompt]
verify_jwt = false

[functions.comfyui-proxy]
verify_jwt = false

[functions.retrieve-predictions]
verify_jwt = false
