project_id = "qyritntnyigmustviepw"

[functions.analyze-lyrics]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-batch-images]
verify_jwt = false

[functions.generate-video]
verify_jwt = false
